
baseurl = 'https://docs.pco.get-cloud.io/'
contentdir = 'content/en'
defaultcontentlanguage = 'en'

enablegitinfo = true
enablemissingtranslationplaceholders = true
enablerobotstxt = true

languagecode = 'en-us'

publishdir = 'public'
staticdir = ['static']

title = 'pluscloud open'
titlecasestyle = 'AP'

[frontmatter]
  date = ['date', 'publishdate', 'pubdate', 'published', 'lastmod', 'modified']
  expirydate = ['expirydate', 'unpublishdate']
  lastmod = [':git', 'lastmod', 'modified', 'date', 'publishdate', 'pubdate', 'published']
  publishdate = ['publishdate', 'pubdate', 'published', 'date']

[imaging]
  anchor = 'smart'
  quality = 75
  # https://gohugo.io/content-management/image-processing/#resampling-filter
  resamplefilter = 'CatmullRom'

  [imaging.exif]
    disablelatlong = true

[languages]
  [languages.en]
    languagename = 'English'
    title = 'pluscloud open'
    weight = 10

    [languages.en.params]
      description = 'The technical documentation for pluscloud open'
      time_format_blog = '02.01.2006'
      time_format_default = '02.01.2006'

  [languages.de]
    disabled = true
    languagename = 'Deutsch'
    title = 'pluscloud open'
    weight = 20

    [languages.de.params]
      description = 'Die technische Dokumentation für die pluscloud open'
      time_format_blog = '02.01.2006'
      time_format_default = '02.01.2006'

[markup]
  defaultmarkdownhandler = 'goldmark'

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    guesssyntax = true
    # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
    style = 'github'
    tabwidth = 4

[module]
  proxy = 'direct'

  [module.hugoversion]
    extended = true
    min = '0.119.0'

[[module.imports]]
    path = 'github.com/google/docsy'

[[module.imports]]
    path = 'github.com/google/docsy/dependencies'

[outputs]
  section = ['html', 'rss']

[params]
  copyright = 'plusserver GmbH'
  github_branch = 'main'
  github_repo = 'https://github.com/pluscloudopen/docs'
  offlinesearch = true
  prism_syntax_highlighting = true
  privacy_policy = 'https://www.plusserver.com/en/privacy-policy'

  [params.links]
    # Developer relevant links. These will show up on right side of footer and in the community page if you have one.
    [[params.links.developer]]
      desc = 'plusserver GmbH Contact'
      icon = 'fa-solid fa-phone'
      name = 'Contact'
      url = 'https://www.plusserver.com/en/about-us/plusserver-contact'

    [[params.links.developer]]
      desc = 'plusserver GmbH Legal notice'
      icon = 'fa-solid fa-gavel'
      name = 'Company Information'
      theme = ['github.com/google/docsy', 'github.com/google/docsy/dependencies']
      url = 'https://www.plusserver.com/en/company-information'

    # End user relevant links. These will show up on left side of footer and in the community page if you have one.
    [[params.links.user]]
      desc = 'pluscloud open product page'
      icon = 'fa-solid fa-house'
      name = 'pluscloud open'
      url = 'https://www.plusserver.com/en/products/pluscloud-open'

    [[params.links.user]]
      desc = 'Development takes place here!'
      icon = 'fab fa-github'
      name = 'GitHub'
      url = 'https://github.com/pluscloudopen'

  [params.taxonomy]
    pygmentscodefences = true
    pygmentsstyle = 'tango'
    taxonomycloud = ['tags', 'categories']
    taxonomycloudtitle = ['Tag Cloud', 'Categories']
    taxonomypageheader = ['tags', 'categories']

  [params.ui]
    footer_about_disable = true
    navbar_logo = true
    sidebar_menu_compact = true
    sidebar_menu_foldable = true

    [params.ui.feedback]
      no = 'Sorry to hear that. Please <a href="https://github.com/pluscloudopen/docs/issues/new">tell us how we can improve</a>.'
      yes = 'Glad to hear it! Please <a href="https://github.com/pluscloudopen/docs/issues/new">tell us how we can improve</a>.'

    [params.ui.readingtime]
      enable = true

[permalinks]
  [permalinks.page]
    blog = '/:section/:year/:month/:day/:slug/'

  [permalinks.term]
    blog = '/:section/:year/:month/:day/:slug/'

[privacy]
  [privacy.disqus]

  [privacy.googleanalytics]

  [privacy.instagram]

  [privacy.twitter]

  [privacy.vimeo]

  [privacy.youtube]

[services]
  [services.disqus]

  [services.googleanalytics]

  [services.instagram]

  [services.rss]
    limit = -1

  [services.twitter]

[sitemap]
  filename = 'sitemap.xml'
  priority = -1

[taxonomies]
  category = 'categories'
  tag = 'tags'
